# Generated by Django 4.1 on 2022-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_bilhete_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bilhete",
            constraint=models.UniqueConstraint(
                fields=("numeropoltrona", "num_iti"), name="poltrona-unica"
            ),
        ),
    ]
